// source: presidents.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var president_pb = require('./president_pb.js');
goog.object.extend(proto, president_pb);
goog.exportSymbol('proto.Presidents', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Presidents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Presidents.repeatedFields_, null);
};
goog.inherits(proto.Presidents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Presidents.displayName = 'proto.Presidents';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Presidents.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Presidents.prototype.toObject = function(opt_includeInstance) {
  return proto.Presidents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Presidents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Presidents.toObject = function(includeInstance, msg) {
  var f, obj = {
    presidentList: jspb.Message.toObjectList(msg.getPresidentList(),
    president_pb.President.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Presidents}
 */
proto.Presidents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Presidents;
  return proto.Presidents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Presidents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Presidents}
 */
proto.Presidents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new president_pb.President;
      reader.readMessage(value,president_pb.President.deserializeBinaryFromReader);
      msg.addPresident(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Presidents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Presidents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Presidents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Presidents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPresidentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      president_pb.President.serializeBinaryToWriter
    );
  }
};


/**
 * repeated President president = 1;
 * @return {!Array<!proto.President>}
 */
proto.Presidents.prototype.getPresidentList = function() {
  return /** @type{!Array<!proto.President>} */ (
    jspb.Message.getRepeatedWrapperField(this, president_pb.President, 1));
};


/**
 * @param {!Array<!proto.President>} value
 * @return {!proto.Presidents} returns this
*/
proto.Presidents.prototype.setPresidentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.President=} opt_value
 * @param {number=} opt_index
 * @return {!proto.President}
 */
proto.Presidents.prototype.addPresident = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.President, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Presidents} returns this
 */
proto.Presidents.prototype.clearPresidentList = function() {
  return this.setPresidentList([]);
};


goog.object.extend(exports, proto);
